In [2]:
import pandas as pd
import os

In [3]:
for year in range(2014, 2025):
    filepath = f'../Data/data_raw/LLCP{year}.XPT'
    if not os.path.exists(filepath):
        print(f"{year}: File not found")
        continue
    df = pd.read_sas(filepath, format='xport')
    print(f"\n=== {year} ({len(df.columns)} columns) ===")
    print(sorted(df.columns.tolist()))

=== 2014 (279 columns) ===
['ADDEPEV2', 'ALCDAY5', 'ASACTLIM', 'ASATTACK', 'ASBIADVC', 'ASBIALCH', 'ASBIBING', 'ASBIDRNK', 'ASBIRDUC', 'ASDRVIST', 'ASERVIST', 'ASINHALR', 'ASNOSLEP', 'ASRCHKUP', 'ASTHMA3', 'ASTHMAGE', 'ASTHMED3', 'ASTHNOW', 'ASYMPTOM', 'AVEDRNK2', 'BLDSTOOL', 'BLDSUGAR', 'BLIND', 'CADULT', 'CARERCVD', 'CASTHDX2', 'CASTHNO2', 'CCLGHOUS', 'CELLFON2', 'CHCCOPD1', 'CHCKIDNY', 'CHCOCNCR', 'CHCSCNCR', 'CHECKUP1', 'CHILDREN', 'CHKHEMO3', 'CNCRAGE', 'CNCRDIFF', 'CNCRTYP1', 'COLGHOUS', 'CPDEMO1', 'CSRVCLIN', 'CSRVCTL1', 'CSRVDEIN', 'CSRVDOC1', 'CSRVINSR', 'CSRVINST', 'CSRVPAIN', 'CSRVRTRN', 'CSRVSUM', 'CSRVTRT1', 'CSTATE', 'CTELENUM', 'CTELNUM1', 'CVDCRHD4', 'CVDINFR4', 'CVDSTRK3', 'DECIDE', 'DELAYMED', 'DIABAGE2', 'DIABEDU', 'DIABETE3', 'DIABEYE', 'DIFFALON', 'DIFFDRES', 'DIFFWALK', 'DISPCODE', 'DLYOTHER', 'DOCTDIAB', 'DRADVISE', 'DRNK3GE5', 'DRNKANY5', 'DRNKDRI2', 'DROCDY3_', 'DRVISITS', 'EDUCA', 'EMPLOY1', 'EMTSUPRT', 'EXERANY2', 'EYEEXAM', 'FALL12MN', 'FALLINJ2', 'FEETCHK', 'FEETCHK2', 'FLSHTMY2', 'FLUSHOT6', 'FMONTH', 'GENHLTH', 'HADHYST2', 'HADMAM', 'HADPAP2', 'HADSGCO1', 'HADSIGM3', 'HAVARTH3', 'HEIGHT3', 'HHADULT', 'HIVTST6', 'HIVTSTD3', 'HLTHCVR1', 'HLTHPLN1', 'HOWLONG', 'HPLSTTST', 'HPVADSHT', 'HPVADVC2', 'HPVTEST', 'HTIN4', 'HTM4', 'IDATE', 'IDAY', 'IMFVPLAC', 'IMONTH', 'INCOME2', 'INSULIN', 'INTERNET', 'IYEAR', 'LADULT', 'LANDLINE', 'LASTDEN3', 'LASTPAP2', 'LASTSIG3', 'LASTSMK2', 'LENGEXAM', 'LONGWTCH', 'LSATISFY', 'LSTBLDS3', 'LSTCOVRG', 'MARITAL', 'MAXDRNKS', 'MEDBILL1', 'MEDCOST', 'MEDICARE', 'MEDSCOST', 'MENTHLTH', 'MSCODE', 'NOCOV121', 'NUMADULT', 'NUMHHOL2', 'NUMMEN', 'NUMPHON2', 'NUMWOMEN', 'PAINACT2', 'PCPSAAD2', 'PCPSADI1', 'PCPSARE1', 'PCPSARS1', 'PDIABTST', 'PERSDOC2', 'PHYSHLTH', 'PNEUVAC3', 'POORHLTH', 'PREDIAB1', 'PREGNANT', 'PROFEXAM', 'PSATEST1', 'PSATIME', 'PVTRESD1', 'PVTRESD2', 'QLACTLM2', 'QLHLTH2', 'QLMENTL2', 'QLSTRES2', 'QSTLANG', 'QSTVER', 'RCHISLA1', 'RCSBIRTH', 'RCSBRAC1', 'RCSGENDR', 'RCSRACE1', 'RCSRLTN2', 'RENTHOM1', 'RMVTETH3', 'RRATWRK2', 'RRCLASS2', 'RRCOGNT2', 'RREMTSM2', 'RRHCARE3', 'RRPHYSM2', 'SCNTLPAD', 'SCNTLWK1', 'SCNTMEL1', 'SCNTMNY1', 'SCNTPAID', 'SCNTVOT1', 'SCNTWRK1', 'SEATBELT', 'SEQNO', 'SEX', 'SHINGLE2', 'SLEPTIM1', 'SMOKDAY2', 'SMOKE100', 'STATERES', 'STOPSMK2', 'SXORIENT', 'TETANUS', 'TRNSGNDR', 'USEEQUIP', 'USENOW3', 'VETERAN3', 'WEIGHT2', 'WHRTST10', 'WTCHSALT', 'WTKG3', '_AGE65YR', '_AGE80', '_AGEG5YR', '_AGE_G', '_AIDTST3', '_ALTETH2', '_ASTHMS1', '_BMI5', '_BMI5CAT', '_CASTHM1', '_CHISPNC', '_CHLDCNT', '_CLLCPWT', '_COL10YR', '_CPRACE', '_CRACE1', '_CRCREC', '_DENVST2', '_DRDXAR1', '_DRNKDY4', '_DRNKMO4', '_DUALCOR', '_DUALUSE', '_EDUCAG', '_EXTETH2', '_FLSHOT6', '_FOBTFS', '_FS5YR', '_HCVU651', '_HFOB3YR', '_HISPANC', '_IMPCAGE', '_IMPCRAC', '_IMPCSEX', '_IMPEDUC', '_IMPHOME', '_IMPMRTL', '_IMPNPH', '_IMPRACE', '_INCOMG', '_LLCPWT', '_LLCPWT2', '_LTASTH1', '_MAM5021', '_MAM502Y', '_MRACE1', '_PNEUMO2', '_PRACE1', '_PSU', '_RACE', '_RACEG21', '_RACEGR3', '_RACE_G1', '_RAWRAKE', '_RFBING5', '_RFBLDS2', '_RFBLDS3', '_RFBMI5', '_RFDRHV4', '_RFDRMN4', '_RFDRWM4', '_RFHLTH', '_RFMAM2Y', '_RFPAP32', '_RFPAP33', '_RFPSA21', '_RFSEAT2', '_RFSEAT3', '_RFSIGM2', '_RFSMOK3', '_SMOKER3', '_STATE', '_STRWT', '_STSTR', '_TOTINDA', '_WT2RAKE']

=== 2015 (330 columns) ===
['ACTIN11_', 'ACTIN21_', 'ADANXEV', 'ADDEPEV2', 'ADDOWN', 'ADEAT1', 'ADENERGY', 'ADFAIL', 'ADMOVE', 'ADPLEASR', 'ADSLEEP', 'ADTHINK', 'ALCDAY5', 'ARTHDIS2', 'ARTHEDU', 'ARTHEXER', 'ARTHSOCL', 'ARTHWGT', 'ARTTODAY', 'ASACTLIM', 'ASATTACK', 'ASDRVIST', 'ASERVIST', 'ASINHALR', 'ASNOSLEP', 'ASPUNSAF', 'ASRCHKUP', 'ASTHMA3', 'ASTHMAGE', 'ASTHMED3', 'ASTHNOW', 'ASYMPTOM', 'AVEDRNK2', 'BEANDAY_', 'BLDSTOOL', 'BLDSUGAR', 'BLIND', 'BLOODCHO', 'BPHIGH4', 'BPMEDS', 'CADULT', 'CAREGIV1', 'CASTHDX2', 'CASTHNO2', 'CCLGHOUS', 'CDASSIST', 'CDDISCUS', 'CDHELP', 'CDHOUSE', 'CDSOCIAL', 'CELLFON2', 'CELLFON3', 'CHCCOPD1', 'CHCKIDNY', 'CHCOCNCR', 'CHCSCNCR', 'CHECKUP1', 'CHILDREN', 'CHKHEMO3', 'CHOLCHK', 'CIMEMLOS', 'COLGHOUS', 'CPDEMO1', 'CRGVEXPT', 'CRGVHOUS', 'CRGVHRS1', 'CRGVLNG1', 'CRGVMST2', 'CRGVPERS', 'CRGVPRB1', 'CRGVREL1', 'CSTATE', 'CTELENUM', 'CTELNUM1', 'CVDASPRN', 'CVDCRHD4', 'CVDINFR4', 'CVDSTRK3', 'DECIDE', 'DIABAGE2', 'DIABEDU', 'DIABETE3', 'DIABEYE', 'DIFFALON', 'DIFFDRES', 'DIFFWALK', 'DISPCODE', 'DOCTDIAB', 'DRADVISE', 'DRNK3GE5', 'DRNKANY5', 'DROCDY3_', 'EDUCA', 'EMPLOY1', 'EMTSUPRT', 'EXACTOT1', 'EXACTOT2', 'EXERANY2', 'EXERHMM1', 'EXERHMM2', 'EXEROFT1', 'EXEROFT2', 'EXRACT11', 'EXRACT21', 'EYEEXAM', 'FC60_', 'FEETCHK', 'FEETCHK2', 'FLSHTMY2', 'FLUSHOT6', 'FMONTH', 'FRUIT1', 'FRUITJU1', 'FRUTDA1_', 'FTJUDA1_', 'FVBEANS', 'FVGREEN', 'FVORANG', 'GENHLTH', 'GRENDAY_', 'HADHYST2', 'HADMAM', 'HADPAP2', 'HADSGCO1', 'HADSIGM3', 'HAREHAB1', 'HAVARTH3', 'HEIGHT3', 'HHADULT', 'HIVTST6', 'HIVTSTD3', 'HLTHPLN1', 'HOWLONG', 'HPLSTTST', 'HPVADSHT', 'HPVADVC2', 'HPVTEST', 'HTIN4', 'HTM4', 'IDATE', 'IDAY', 'IMFVPLAC', 'IMONTH', 'INCOME2', 'INSULIN', 'INTERNET', 'IYEAR', 'JOINPAIN', 'LADULT', 'LANDLINE', 'LASTPAP2', 'LASTSIG3', 'LASTSMK2', 'LENGEXAM', 'LMTJOIN3', 'LONGWTCH', 'LSATISFY', 'LSTBLDS3', 'MARITAL', 'MAXDRNKS', 'MAXVO2_', 'MEDCOST', 'MENTHLTH', 'METVL11_', 'METVL21_', 'MISTMNT', 'MSCODE', 'NUMADULT', 'NUMHHOL2', 'NUMMEN', 'NUMPHON2', 'NUMWOMEN', 'ORNGDAY_', 'PA1MIN_', 'PA1VIGM_', 'PADUR1_', 'PADUR2_', 'PAFREQ1_', 'PAFREQ2_', 'PAINACT2', 'PAMIN11_', 'PAMIN21_', 'PAMISS1_', 'PAVIG11_', 'PAVIG21_', 'PCDMDECN', 'PCPSAAD2', 'PCPSADE1', 'PCPSADI1', 'PCPSARE1', 'PCPSARS1', 'PDIABTST', 'PERSDOC2', 'PHYSHLTH', 'PNEUVAC3', 'POORHLTH', 'PREDIAB1', 'PREGNANT', 'PROFEXAM', 'PSATEST1', 'PSATIME', 'PVTRESD1', 'PVTRESD2', 'QLACTLM2', 'QLHLTH2', 'QLMENTL2', 'QLSTRES2', 'QSTLANG', 'QSTVER', 'RCSGENDR', 'RCSRLTN2', 'RDUCHART', 'RDUCSTRK', 'RENTHOM1', 'RLIVPAIN', 'SCNTLPAD', 'SCNTLWK1', 'SCNTMEL1', 'SCNTMNY1', 'SCNTPAID', 'SCNTWRK1', 'SEATBELT', 'SEQNO', 'SEX', 'SHINGLE2', 'SMOKDAY2', 'SMOKE100', 'STATERES', 'STOPSMK2', 'STREHAB1', 'STRENGTH', 'STRFREQ_', 'SXORIENT', 'TETANUS', 'TOLDHI2', 'TRNSGNDR', 'USEEQUIP', 'USENOW3', 'VEGEDA1_', 'VEGETAB1', 'VETERAN3', 'VICTRCT4', 'VIDFCLT2', 'VIEYEXM2', 'VIGLUMA2', 'VIINSUR2', 'VIMACDG2', 'VINOCRE2', 'VIPRFVS2', 'VIREDIF3', 'WEIGHT2', 'WHRTST10', 'WTCHSALT', 'WTKG3', '_AGE65YR', '_AGE80', '_AGEG5YR', '_AGE_G', '_AIDTST3', '_ASTHMS1', '_BMI5', '_BMI5CAT', '_CASTHM1', '_CHISPNC', '_CHLDCNT', '_CHOLCHK', '_CLLCPWT', '_CPRACE', '_CRACE1', '_DRDXAR1', '_DRNKWEK', '_DUALCOR', '_DUALUSE', '_EDUCAG', '_FLSHOT6', '_FRT16', '_FRTLT1', '_FRTRESP', '_FRUITEX', '_FRUTSUM', '_HCVU651', '_HISPANC', '_INCOMG', '_LLCPWT', '_LMTACT1', '_LMTSCL1', '_LMTWRK1', '_LTASTH1', '_MICHD', '_MINAC11', '_MINAC21', '_MISFRTN', '_MISVEGN', '_MRACE1', '_PA150R2', '_PA30021', '_PA300R2', '_PACAT1', '_PAINDX1', '_PAREC1', '_PASTAE1', '_PASTRNG', '_PNEUMO2', '_PRACE1', '_PSU', '_RACE', '_RACEG21', '_RACEGR3', '_RACE_G1', '_RAWRAKE', '_RFBING5', '_RFBMI5', '_RFCHOL', '_RFDRHV5', '_RFHLTH', '_RFHYPE5', '_RFSEAT2', '_RFSEAT3', '_RFSMOK3', '_SMOKER3', '_STATE', '_STRWT', '_STSTR', '_TOTINDA', '_VEG23', '_VEGESUM', '_VEGETEX', '_VEGLT1', '_VEGRESP', '_WT2RAKE']

=== 2016 (275 columns) ===
['ADDEPEV2', 'ALCDAY5', 'ASACTLIM', 'ASATTACK', 'ASDRVIST', 'ASERVIST', 'ASINHALR', 'ASNOSLEP', 'ASRCHKUP', 'ASTHMA3', 'ASTHMAGE', 'ASTHMED3', 'ASTHNOW', 'ASYMPTOM', 'AVEDRNK2', 'BLDSTOOL', 'BLDSUGAR', 'BLIND', 'CADULT', 'CALRINFO', 'CAREGIV1', 'CARERCVD', 'CASTHDX2', 'CASTHNO2', 'CCLGHOUS', 'CDASSIST', 'CDDISCUS', 'CDHELP', 'CDHOUSE', 'CDSOCIAL', 'CELLFON4', 'CELLFON5', 'CHCCOPD1', 'CHCKIDNY', 'CHCOCNCR', 'CHCSCNCR', 'CHECKUP1', 'CHILDREN', 'CHKHEMO3', 'CIMEMLOS', 'CNCRAGE', 'CNCRDIFF', 'CNCRTYP1', 'COLGHOUS', 'CPDEMO1', 'CRGVEXPT', 'CRGVHOUS', 'CRGVHRS1', 'CRGVLNG1', 'CRGVMST2', 'CRGVPERS', 'CRGVPRB2', 'CRGVREL1', 'CSRVCLIN', 'CSRVCTL1', 'CSRVDEIN', 'CSRVDOC1', 'CSRVINSR', 'CSRVINST', 'CSRVPAIN', 'CSRVRTRN', 'CSRVSUM', 'CSRVTRT1', 'CSTATE1', 'CTELENM1', 'CTELNUM1', 'CVDCRHD4', 'CVDINFR4', 'CVDSTRK3', 'DEAF', 'DECIDE', 'DELAYMED', 'DIABAGE2', 'DIABEDU', 'DIABETE3', 'DIABEYE', 'DIFFALON', 'DIFFDRES', 'DIFFWALK', 'DISPCODE', 'DLYOTHER', 'DOCTDIAB', 'DRNK3GE5', 'DRNKANY5', 'DRNKDRI2', 'DROCDY3_', 'DRVISITS', 'ECIGARET', 'ECIGNOW', 'EDUCA', 'EMPLOY1', 'EMTSUPRT', 'EXERANY2', 'EYEEXAM', 'FALL12MN', 'FALLINJ2', 'FEETCHK', 'FEETCHK2', 'FLSHTMY2', 'FLUSHOT6', 'FMONTH', 'GENHLTH', 'HADHYST2', 'HADMAM', 'HADPAP2', 'HADSGCO1', 'HADSIGM3', 'HAVARTH3', 'HEIGHT3', 'HHADULT', 'HIVRISK4', 'HIVTST6', 'HIVTSTD3', 'HLTHCVR1', 'HLTHPLN1', 'HOWLONG', 'HPLSTTST', 'HPVADSHT', 'HPVADVC2', 'HPVTEST', 'HTIN4', 'HTM4', 'IDATE', 'IDAY', 'IMFVPLAC', 'IMONTH', 'INCOME2', 'INSULIN', 'INTERNET', 'IYEAR', 'LADULT', 'LANDLINE', 'LASTDEN3', 'LASTPAP2', 'LASTSIG3', 'LASTSMK2', 'LENGEXAM', 'LSATISFY', 'LSTBLDS3', 'LSTCOVRG', 'MARIJANA', 'MARITAL', 'MAXDRNKS', 'MEDADVIC', 'MEDBILL1', 'MEDCOST', 'MEDICARE', 'MEDSCOST', 'MENTHLTH', 'MSCODE', 'NOCOV121', 'NUMADULT', 'NUMBURN2', 'NUMHHOL2', 'NUMMEN', 'NUMPHON2', 'NUMWOMEN', 'PAINACT2', 'PCDMDECN', 'PCPSAAD2', 'PCPSADE1', 'PCPSADI1', 'PCPSARE1', 'PCPSARS1', 'PDIABTST', 'PERSDOC2', 'PHYSHLTH', 'PNEUVAC3', 'POORHLTH', 'PREDIAB1', 'PREGNANT', 'PROFEXAM', 'PSATEST1', 'PSATIME', 'PVTRESD1', 'PVTRESD3', 'QLACTLM2', 'QLHLTH2', 'QLMENTL2', 'QLSTRES2', 'QSTLANG', 'QSTVER', 'RCSGENDR', 'RCSRLTN2', 'RENTHOM1', 'RMVTETH3', 'SEATBELT', 'SEQNO', 'SEX', 'SHINGLE2', 'SLEPTIM1', 'SMOKDAY2', 'SMOKE100', 'SSBFRUT2', 'SSBSUGR2', 'STATERES', 'STOPSMK2', 'SXORIENT', 'TETANUS', 'TRNSGNDR', 'UNDRSTND', 'USEEQUIP', 'USEMRJNA', 'USENOW3', 'VETERAN3', 'WEIGHT2', 'WRITTEN', 'WTKG3', '_AGE65YR', '_AGE80', '_AGEG5YR', '_AGE_G', '_AIDTST3', '_ALTETH2', '_ASTHMS1', '_BMI5', '_BMI5CAT', '_CASTHM1', '_CHISPNC', '_CHLDCNT', '_CLLCPWT', '_COL10YR', '_CPRACE', '_CRACE1', '_CRCREC', '_CURECIG', '_DENVST2', '_DRDXAR1', '_DRNKDRV', '_DRNKWEK', '_DUALCOR', '_DUALUSE', '_ECIGSTS', '_EDUCAG', '_EXTETH2', '_FLSHOT6', '_FOBTFS', '_FS5YR', '_HCVU651', '_HFOB3YR', '_HISPANC', '_INCOMG', '_LLCPWT', '_LLCPWT2', '_LTASTH1', '_MAM5021', '_MENT14D', '_MICHD', '_MRACE1', '_PHYS14D', '_PNEUMO2', '_PRACE1', '_PSU', '_RACE', '_RACEG21', '_RACEGR3', '_RACE_G1', '_RAWRAKE', '_RFBING5', '_RFBLDS3', '_RFBMI5', '_RFDRHV5', '_RFHLTH', '_RFMAM2Y', '_RFPAP33', '_RFPSA21', '_RFSEAT2', '_RFSEAT3', '_RFSMOK3', '_SMOKER3', '_STATE', '_STRWT', '_STSTR', '_TOTINDA', '_WT2RAKE']

=== 2017 (358 columns) ===
['ACTIN11_', 'ACTIN21_', 'ADDEPEV2', 'ADSLEEP', 'ALCDAY5', 'ARTHDIS2', 'ARTHEDU', 'ARTHEXER', 'ARTHSOCL', 'ARTHWGT', 'ARTTODAY', 'ASACTLIM', 'ASATTACK', 'ASBIADVC', 'ASBIALCH', 'ASBIBING', 'ASBIDRNK', 'ASBIRDUC', 'ASDRVIST', 'ASERVIST', 'ASINHALR', 'ASNOSLEP', 'ASPUNSAF', 'ASRCHKUP', 'ASTHMA3', 'ASTHMAGE', 'ASTHMED3', 'ASTHNOW', 'ASYMPTOM', 'AVEDRNK2', 'BLDSUGAR', 'BLIND', 'BPALCADV', 'BPALCHOL', 'BPEATADV', 'BPEATHBT', 'BPEXER', 'BPEXRADV', 'BPHI2MR', 'BPHIGH4', 'BPMEDADV', 'BPMEDS', 'BPSALT', 'BPSLTADV', 'CADULT', 'CAREGIV1', 'CARERCVD', 'CASTHDX2', 'CASTHNO2', 'CCLGHOUS', 'CDASSIST', 'CDDISCUS', 'CDHELP', 'CDHOUSE', 'CDSOCIAL', 'CELLFON4', 'CELLFON5', 'CHCCOPD1', 'CHCKIDNY', 'CHCOCNCR', 'CHCSCNCR', 'CHECKUP1', 'CHILDREN', 'CHKHEMO3', 'CHOLCHK1', 'CHOLMED1', 'CIMEMLOS', 'CNCRAGE', 'CNCRDIFF', 'CNCRTYP1', 'COLGHOUS', 'COPDBRTH', 'COPDBTST', 'COPDCOGH', 'COPDFLEM', 'COPDSMOK', 'CPDEMO1A', 'CRGVEXPT', 'CRGVHOUS', 'CRGVHRS1', 'CRGVLNG1', 'CRGVMST2', 'CRGVPERS', 'CRGVPRB2', 'CRGVREL2', 'CSRVCLIN', 'CSRVCTL1', 'CSRVDEIN', 'CSRVDOC1', 'CSRVINSR', 'CSRVINST', 'CSRVPAIN', 'CSRVRTRN', 'CSRVSUM', 'CSRVTRT2', 'CSTATE1', 'CTELENM1', 'CTELNUM1', 'CVDASPRN', 'CVDCRHD4', 'CVDINFR4', 'CVDSTRK3', 'DEAF', 'DECIDE', 'DELAYMED', 'DIABAGE2', 'DIABEDU', 'DIABETE3', 'DIABEYE', 'DIFFALON', 'DIFFDRES', 'DIFFWALK', 'DISPCODE', 'DLYOTHER', 'DOCTDIAB', 'DRADVISE', 'DRNK3GE5', 'DRNKANY5', 'DROCDY3_', 'DRVISITS', 'ECIGARET', 'ECIGNOW', 'EDUCA', 'EMPLOY1', 'EMTSUPRT', 'EXERANY2', 'EXERHMM1', 'EXERHMM2', 'EXEROFT1', 'EXEROFT2', 'EXRACT11', 'EXRACT21', 'EYEEXAM', 'FC60_', 'FEETCHK', 'FEETCHK2', 'FIREARM4', 'FLSHTMY2', 'FLUSHOT6', 'FMONTH', 'FRENCHF1', 'FRNCHDA_', 'FRUIT2', 'FRUITJU2', 'FRUTDA2_', 'FTJUDA2_', 'FVGREEN1', 'GENHLTH', 'GRENDA1_', 'GUNLOAD', 'HAREHAB1', 'HAVARTH3', 'HEIGHT3', 'HHADULT', 'HIVRISK5', 'HIVTST6', 'HIVTSTD3', 'HLTHCVR1', 'HLTHPLN1', 'HOWSAFE1', 'HPVADSHT', 'HPVADVC2', 'HTIN4', 'HTM4', 'IDATE', 'IDAY', 'IMFVPLAC', 'IMONTH', 'INCOME2', 'INSULIN', 'INTERNET', 'IYEAR', 'JOINPAI1', 'LADULT', 'LANDLINE', 'LASTSMK2', 'LCSCTSCN', 'LCSFIRST', 'LCSLAST', 'LCSNUMCG', 'LMTJOIN3', 'LOADULK2', 'LSATISFY', 'LSTCOVRG', 'MARIJANA', 'MARITAL', 'MAXDRNKS', 'MAXVO2_', 'MEDBILL1', 'MEDCOST', 'MEDICARE', 'MEDSCOS1', 'MENTHLTH', 'METVL11_', 'METVL21_', 'MSCODE', 'NOBCUSE6', 'NOCOV121', 'NUMADULT', 'NUMHHOL2', 'NUMMEN', 'NUMPHON2', 'NUMWOMEN', 'PA1MIN_', 'PA1VIGM_', 'PADUR1_', 'PADUR2_', 'PAFREQ1_', 'PAFREQ2_', 'PAINACT2', 'PAMIN11_', 'PAMIN21_', 'PAMISS1_', 'PAVIG11_', 'PAVIG21_', 'PDIABTST', 'PERSDOC2', 'PFPPRVN2', 'PHYSHLTH', 'PNEUVAC3', 'POORHLTH', 'POTADA1_', 'POTATOE1', 'PREDIAB1', 'PREGNANT', 'PVTRESD1', 'PVTRESD3', 'QLHLTH2', 'QLMENTL2', 'QLSTRES2', 'QSTLANG', 'QSTVER', 'RCSGENDR', 'RCSRLTN2', 'RDUCHART', 'RDUCSTRK', 'RENTHOM1', 'RLIVPAIN', 'RSNMRJNA', 'SAFETIME', 'SDHBILLS', 'SDHFOOD', 'SDHMEALS', 'SDHMONEY', 'SDHMOVE', 'SDHSTRES', 'SEATBELT', 'SEQNO', 'SEX', 'SHINGLE2', 'SLEPBRTH', 'SLEPDAY1', 'SLEPSNO2', 'SLEPTIM1', 'SMOKDAY2', 'SMOKE100', 'SSBFRUT3', 'SSBSUGR2', 'STATERE1', 'STOPSMK2', 'STREHAB1', 'STRENGTH', 'STRFREQ_', 'SXORIENT', 'TETANUS', 'TOLDHI2', 'TRNSGNDR', 'TYPCNTR7', 'USEMRJN1', 'USENOW3', 'VEGEDA2_', 'VEGETAB2', 'VETERAN3', 'WEIGHT2', 'WTCHSALT', 'WTKG3', '_AGE65YR', '_AGE80', '_AGEG5YR', '_AGE_G', '_AIDTST3', '_ASTHMS1', '_BMI5', '_BMI5CAT', '_CASTHM1', '_CHISPNC', '_CHLDCNT', '_CHOLCH1', '_CLLCPWT', '_CPRACE', '_CRACE1', '_CURECIG', '_DRDXAR1', '_DRNKWEK', '_DUALCOR', '_DUALUSE', '_ECIGSTS', '_EDUCAG', '_FLSHOT6', '_FRT16A', '_FRTLT1A', '_FRTRES1', '_FRUITE1', '_FRUTSU1', '_HCVU651', '_HISPANC', '_IMPRACE', '_INCOMG', '_LLCPWT', '_LLCPWT2', '_LMTACT1', '_LMTSCL1', '_LMTWRK1', '_LTASTH1', '_MENT14D', '_MICHD', '_MINAC11', '_MINAC21', '_MISFRT1', '_MISVEG1', '_MRACE1', '_PA150R2', '_PA30021', '_PA300R2', '_PACAT1', '_PAINDX1', '_PAREC1', '_PASTAE1', '_PASTRNG', '_PHYS14D', '_PNEUMO2', '_PRACE1', '_PSU', '_RACE', '_RACEG21', '_RACEGR3', '_RACE_G1', '_RAWRAKE', '_RFBING5', '_RFBMI5', '_RFCHOL1', '_RFDRHV5', '_RFHLTH', '_RFHYPE5', '_RFSEAT2', '_RFSEAT3', '_RFSMOK3', '_SMOKER3', '_STATE', '_STRWT', '_STSTR', '_TOTINDA', '_VEG23A', '_VEGESU1', '_VEGETE1', '_VEGLT1A', '_VEGRES1', '_WT2RAKE']

=== 2018 (275 columns) ===
['ADDEPEV2', 'ADDOWN1', 'ADPLEAS1', 'ADSLEEP', 'ALCDAY5', 'ASTHMA3', 'ASTHNOW', 'AVEDRNK2', 'BLDSTOOL', 'BLDSUGAR', 'BLIND', 'CADULT', 'CAREGIV1', 'CARERCVD', 'CASTHDX2', 'CASTHNO2', 'CCLGHOUS', 'CDASSIST', 'CDDISCUS', 'CDHELP', 'CDHOUSE', 'CDSOCIAL', 'CELLFON4', 'CELLFON5', 'CHCCOPD1', 'CHCKDNY1', 'CHCOCNCR', 'CHCSCNCR', 'CHECKUP1', 'CHILDREN', 'CHKHEMO3', 'CIMEMLOS', 'CNCRAGE', 'CNCRDIFF', 'CNCRTYP1', 'COLGHOUS', 'COPDBRTH', 'COPDBTST', 'COPDCOGH', 'COPDFLEM', 'COPDSMOK', 'CPDEMO1B', 'CRGVEXPT', 'CRGVHOUS', 'CRGVHRS1', 'CRGVLNG1', 'CRGVMST3', 'CRGVPERS', 'CRGVPRB2', 'CRGVREL2', 'CSRVCLIN', 'CSRVCTL1', 'CSRVDEIN', 'CSRVDOC1', 'CSRVINSR', 'CSRVINST', 'CSRVPAIN', 'CSRVRTRN', 'CSRVSUM', 'CSRVTRT2', 'CSTATE1', 'CTELENM1', 'CTELNUM1', 'CVDCRHD4', 'CVDINFR4', 'CVDSTRK3', 'DEAF', 'DECIDE', 'DELAYME1', 'DIABAGE2', 'DIABEDU', 'DIABETE3', 'DIABEYE', 'DIFFALON', 'DIFFDRES', 'DIFFWALK', 'DISPCODE', 'DLYOTHER', 'DOCTDIAB', 'DRNK3GE5', 'DRNKANY5', 'DRNKDRI2', 'DROCDY3_', 'DRVISITS', 'ECIGARET', 'ECIGNOW', 'EDUCA', 'EMPLOY1', 'EXERANY2', 'EYEEXAM1', 'FALL12MN', 'FALLINJ3', 'FEELNERV', 'FEETCHK', 'FEETCHK3', 'FLSHTMY2', 'FLUSHOT6', 'FMONTH', 'GENHLTH', 'HADHYST2', 'HADMAM', 'HADPAP2', 'HADSGCO1', 'HADSIGM3', 'HAVARTH3', 'HEIGHT3', 'HHADULT', 'HIVRISK5', 'HIVTST6', 'HIVTSTD3', 'HLTHCVR1', 'HLTHPLN1', 'HOWLONG', 'HPLSTTST', 'HPVADSHT', 'HPVADVC2', 'HPVTEST', 'HTIN4', 'HTM4', 'IDATE', 'IDAY', 'IMFVPLAC', 'IMONTH', 'INCOME2', 'INDORTAN', 'INSULIN', 'IYEAR', 'LADULT', 'LANDLINE', 'LASTDEN4', 'LASTPAP2', 'LASTSIG3', 'LASTSMK2', 'LCSCTSCN', 'LCSFIRST', 'LCSLAST', 'LCSNUMCG', 'LENGEXAM', 'LSTBLDS3', 'LSTCOVRG', 'MARIJAN1', 'MARITAL', 'MAXDRNKS', 'MEDBILL1', 'MEDCOST', 'MEDICARE', 'MEDSCOS1', 'MENTHLTH', 'MSCODE', 'NOCOV121', 'NUMADULT', 'NUMBURN3', 'NUMHHOL3', 'NUMMEN', 'NUMPHON3', 'NUMWOMEN', 'PCDMDEC1', 'PCPSAAD3', 'PCPSADE1', 'PCPSADI1', 'PCPSARE1', 'PCPSARS1', 'PDIABTST', 'PERSDOC2', 'PHYSHLTH', 'PNEUVAC4', 'POORHLTH', 'PREDIAB1', 'PREGNANT', 'PROFEXAM', 'PSATEST1', 'PSATIME', 'PVTRESD1', 'PVTRESD3', 'QSTLANG', 'QSTVER', 'RCSGENDR', 'RCSRLTN2', 'RENTHOM1', 'RMVTETH4', 'RSNMRJN1', 'SAFETIME', 'SEATBELT', 'SEQNO', 'SEX1', 'SHINGLE2', 'SLEPBRTH', 'SLEPDAY1', 'SLEPSNO2', 'SLEPTIM1', 'SMOKDAY2', 'SMOKE100', 'SOFEMALE', 'SOMALE', 'STATERE1', 'STOPSMK2', 'STOPWORY', 'SUNPRTCT', 'TETANUS1', 'TRNSGNDR', 'USEMRJN2', 'USENOW3', 'VETERAN3', 'WEIGHT2', 'WKDAYOUT', 'WKENDOUT', 'WTKG3', '_AGE65YR', '_AGE80', '_AGEG5YR', '_AGE_G', '_AIDTST3', '_ALTETH3', '_ASTHMS1', '_BMI5', '_BMI5CAT', '_CASTHM1', '_CHISPNC', '_CHLDCNT', '_CLLCPWT', '_COL10YR', '_CPRACE', '_CRACE1', '_CRCREC', '_DENVST3', '_DRDXAR1', '_DRNKDRV', '_DRNKWEK', '_DUALCOR', '_DUALUSE', '_EDUCAG', '_EXTETH3', '_FLSHOT6', '_FOBTFS', '_FS5YR', '_HCVU651', '_HFOB3YR', '_HISPANC', '_IMPRACE', '_INCOMG', '_LLCPWT', '_LLCPWT2', '_LTASTH1', '_MAM5022', '_MENT14D', '_METSTAT', '_MICHD', '_MRACE1', '_PHYS14D', '_PNEUMO3', '_PRACE1', '_PSU', '_RACE', '_RACEG21', '_RACEGR3', '_RACE_G1', '_RAWRAKE', '_RFBING5', '_RFBLDS3', '_RFBMI5', '_RFDRHV6', '_RFHLTH', '_RFMAM21', '_RFPAP34', '_RFPSA22', '_RFSEAT2', '_RFSEAT3', '_RFSMOK3', '_SMOKER3', '_STATE', '_STRWT', '_STSTR', '_TOTINDA', '_URBSTAT', '_WT2RAKE']

=== 2019 (342 columns) ===

In [20]:
vars_to_check = ['HLTHPLN', 'PERSDOC', 'MEDCOST', 'DRVISIT', 'SLEPTIM']

for year in [2021, 2022, 2023, 2024]:
    filepath = f'../Data/data_raw/LLCP{year}.XPT'
    df = pd.read_sas(filepath, format='xport', chunksize=100)
    chunk = next(iter(df))
    print(f"\n=== {year} ===")
    for prefix in vars_to_check:
        matches = [col for col in chunk.columns if col.startswith(prefix)]
        print(f"{prefix}: {matches}")

=== 2021 ===
HLTHPLN: []
PERSDOC: ['PERSDOC3']
MEDCOST: ['MEDCOST1']
DRVISIT: []
SLEPTIM: []

=== 2022 ===
HLTHPLN: []
PERSDOC: ['PERSDOC3']
MEDCOST: ['MEDCOST1']
DRVISIT: []
SLEPTIM: ['SLEPTIM1']

=== 2023 ===
HLTHPLN: []
PERSDOC: ['PERSDOC3']
MEDCOST: ['MEDCOST1']
DRVISIT: []
SLEPTIM: []

=== 2024 ===
HLTHPLN: []
PERSDOC: ['PERSDOC3']
MEDCOST: ['MEDCOST1']
DRVISIT: []
SLEPTIM: []

In [21]:
for year in [2021, 2022, 2023, 2024]:
    filepath = f'../Data/data_raw/LLCP{year}.XPT'
    df = pd.read_sas(filepath, format='xport', chunksize=100)
    chunk = next(iter(df))
    matches = [col for col in chunk.columns if 'HLTH' in col or 'VISIT' in col or 'INSUR' in col or 'PRIM' in col]
    print(f"\n=== {year} ===")
    print(matches)

=== 2021 ===
['GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PRIMINSR', '_RFHLTH', '_HLTHPLN']

=== 2022 ===
['GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PRIMINSR', '_RFHLTH', '_HLTHPLN']

=== 2023 ===
['GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PRIMINS1', '_RFHLTH', '_HLTHPL1']

=== 2024 ===
['GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PRIMINS2', '_RFHLTH', '_HLTHPL2']

In [22]:
vars_to_check = [
    'CVDINFR4', 'CVDCRHD4', 'CVDSTRK3',
    'SMOKE100', 'EXERANY2', 'CHECKUP1',
    'MARITAL', 'EDUCA', '_RACE', '_AGE80',
    'CSRVDOC1', 'CSRVPAIN', '_LLCPWT'
]

for year in range(2014, 2025):
    if year == 2015:
        continue
    filepath = f'../Data/data_raw/LLCP{year}.XPT'
    df = pd.read_sas(filepath, format='xport', chunksize=100)
    chunk = next(iter(df))
    missing = [v for v in vars_to_check if v not in chunk.columns]
    if missing:
        print(f"{year}: Missing → {missing}")
    else:
        print(f"{year}: ✅ All present")

2014: ✅ All present
2016: ✅ All present
2017: ✅ All present
2018: ✅ All present
2019: ✅ All present
2020: ✅ All present
2021: ✅ All present
2022: Missing → ['_RACE']
2023: ✅ All present
2024: ✅ All present

In [23]:
df = pd.read_sas('../Data/data_raw/LLCP2022.XPT', format='xport', chunksize=100)
chunk = next(iter(df))
race_vars = [col for col in chunk.columns if 'RACE' in col]
print(race_vars)

['_IMPRACE', '_CRACE2', '_CPRACE2', '_PRACE2', '_MRACE2', '_RACE1', '_RACEG22', '_RACEGR4', '_RACEPR1']

In [24]:
for year in [2022, 2023, 2024]:
    filepath = f'../Data/data_raw/LLCP{year}.XPT'
    df = pd.read_sas(filepath, format='xport', chunksize=100)
    chunk = next(iter(df))
    race_vars = [col for col in chunk.columns if col.startswith('_RACE')]
    print(f"{year}: {race_vars}")

2022: ['_RACE1', '_RACEG22', '_RACEGR4', '_RACEPR1']
2023: ['_RACE', '_RACEG21', '_RACEGR3', '_RACEPRV']
2024: ['_RACE', '_RACEG21', '_RACEGR3', '_RACEPRV']

In [3]:
# Rename mapping — standardize variable names across years
rename_map = {
    # Sex
    'SEXVAR': 'SEX',
    'SEX1': 'SEX',
    
    # Diabetes
    'DIABETE3': 'DIABETE',
    'DIABETE4': 'DIABETE',
    
    # Depression
    'ADDEPEV2': 'ADDEPEV',
    'ADDEPEV3': 'ADDEPEV',
    
    # Income
    'INCOME2': 'INCOME',
    'INCOME3': 'INCOME',
    
    # Personal doctor
    'PERSDOC2': 'PERSDOC',
    'PERSDOC3': 'PERSDOC',
    
    # Medical cost barrier
    'MEDCOST': 'MEDCOST_U',
    'MEDCOST1': 'MEDCOST_U',
    
    # Health insurance
    'HLTHPLN1': 'HLTHPLN',
    'PRIMINSR': 'HLTHPLN',
    'PRIMINS1': 'HLTHPLN',
    'PRIMINS2': 'HLTHPLN',
    
    # Cancer type
    'CNCRTYP1': 'CNCRTYP',
    'CNCRTYP2': 'CNCRTYP',
    
    # Cancer treatment
    'CSRVTRT1': 'CSRVTRT',
    'CSRVTRT2': 'CSRVTRT',
    'CSRVTRT3': 'CSRVTRT',
    
    # Race (2022 only)
    '_RACE1': '_RACE'
}

In [4]:
selected_columns = [
    'GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH',
    'CNCRAGE', 'CNCRTYP', 'CSRVTRT', 'CSRVDOC1', 'CSRVPAIN',
    '_AGE80', 'SEX', 'INCOME', 'EDUCA', '_RACE',
    'HLTHPLN', 'PERSDOC', 'MEDCOST_U',
    'DIABETE', 'CVDINFR4', 'CVDCRHD4', 'CVDSTRK3', 'ADDEPEV',
    'SMOKE100', 'EXERANY2', 'SLEPTIM1',
    'IYEAR', '_STATE', 'MARITAL', 'CHECKUP1', 'DRVISITS',
    '_LLCPWT'
]

In [8]:
# Diagnosis for 2015 dataset
df_2015 = pd.read_sas('../Data/data_raw/LLCP2015.XPT', format='xport')

# 1. Check if CNCRAGE exists
print("1. Does CNCRAGE exist?", 'CNCRAGE' in df_2015.columns)

# 2. Check non-null values if it exists
if 'CNCRAGE' in df_2015.columns:
    print("2. Number of non-null values:", df_2015['CNCRAGE'].notna().sum())
    print("   Total rows in 2015 dataset:", len(df_2015))
else:
    # If not found, let's look for alternative cancer age variables
    cancer_cols = [c for c in df_2015.columns if 'CNCR' in c]
    print("   Alternative cancer-related columns found:", cancer_cols)

1. Does CNCRAGE exist? False
   Alternative cancer-related columns found: ['CHCSCNCR', 'CHCOCNCR']

In [9]:
all_years = []

for year in range(2014, 2025):
    # 2015 does not have the detailed cancer survivorship module (CNCRAGE)
    if year == 2015:
        print(f"2015: Skipped — Cancer module / CNCRAGE not available")
        continue
       
    filepath = f'../Data/data_raw/LLCP{year}.XPT'
    if not os.path.exists(filepath):
        print(f"{year}: File not found")
        continue
    
    print(f"Loading {year}...")
    df = pd.read_sas(filepath, format='xport')
    
    # Apply rename mapping
    df = df.rename(columns=rename_map)
    
    # Filter cancer cases only
    if 'CNCRAGE' not in df.columns:
        print(f"{year}: CNCRAGE not found — skipping")
        continue
    df = df[df['CNCRAGE'].notna()]

    
    # Select columns (keep only what exists)
    cols = [c for c in selected_columns if c in df.columns]
    df = df[cols]

    # Add year column
    df['YEAR'] = year
    
    
    all_years.append(df)
    print(f"{year}: {len(df)} cancer cases")

print("\nDone!")

Loading 2014...
2014: 7788 cancer cases
2015: Skipped — Cancer module / CNCRAGE not available
Loading 2016...
2016: 8299 cancer cases
Loading 2017...
2017: 7981 cancer cases
Loading 2018...
2018: 6191 cancer cases
Loading 2019...
2019: 890 cancer cases
Loading 2020...
2020: 22693 cancer cases
Loading 2021...
2021: 9797 cancer cases
Loading 2022...
2022: 22565 cancer cases
Loading 2023...
2023: 16629 cancer cases
Loading 2024...
2024: 14448 cancer cases

Done!

In [32]:
pre = [2014, 2016, 2017, 2018, 2019]
peak = [2020, 2021]
post = [2022, 2023, 2024]

for period, years in [('Pre-Pandemic', pre), ('Pandemic Peak', peak), ('Pandemic Recovery', post)]:
    total = sum(len(df) for df in all_years if df['YEAR'].iloc[0] in years)
    print(f"{period}: {total} cancer cases")

Pre-Pandemic: 31149 cancer cases
Pandemic Peak: 32490 cancer cases
Pandemic Recovery: 53642 cancer cases

In [33]:
for df in all_years:
    year = int(df['YEAR'].iloc[0])
    print(f"{year}: {len(df.columns)} columns → {sorted(df.columns.tolist())}")

2014: 32 columns → ['ADDEPEV', 'CHECKUP1', 'CNCRAGE', 'CNCRTYP', 'CSRVDOC1', 'CSRVPAIN', 'CSRVTRT', 'CVDCRHD4', 'CVDINFR4', 'CVDSTRK3', 'DIABETE', 'DRVISITS', 'EDUCA', 'EXERANY2', 'GENHLTH', 'HLTHPLN', 'INCOME', 'IYEAR', 'MARITAL', 'MEDCOST_U', 'MENTHLTH', 'PERSDOC', 'PHYSHLTH', 'POORHLTH', 'SEX', 'SLEPTIM1', 'SMOKE100', 'YEAR', '_AGE80', '_LLCPWT', '_RACE', '_STATE']
2016: 32 columns → ['ADDEPEV', 'CHECKUP1', 'CNCRAGE', 'CNCRTYP', 'CSRVDOC1', 'CSRVPAIN', 'CSRVTRT', 'CVDCRHD4', 'CVDINFR4', 'CVDSTRK3', 'DIABETE', 'DRVISITS', 'EDUCA', 'EXERANY2', 'GENHLTH', 'HLTHPLN', 'INCOME', 'IYEAR', 'MARITAL', 'MEDCOST_U', 'MENTHLTH', 'PERSDOC', 'PHYSHLTH', 'POORHLTH', 'SEX', 'SLEPTIM1', 'SMOKE100', 'YEAR', '_AGE80', '_LLCPWT', '_RACE', '_STATE']
2017: 32 columns → ['ADDEPEV', 'CHECKUP1', 'CNCRAGE', 'CNCRTYP', 'CSRVDOC1', 'CSRVPAIN', 'CSRVTRT', 'CVDCRHD4', 'CVDINFR4', 'CVDSTRK3', 'DIABETE', 'DRVISITS', 'EDUCA', 'EXERANY2', 'GENHLTH', 'HLTHPLN', 'INCOME', 'IYEAR', 'MARITAL', 'MEDCOST_U', 'MENTHLTH', 'PERSDOC', 'PHYSHLTH', 'POORHLTH', 'SEX', 'SLEPTIM1', 'SMOKE100', 'YEAR', '_AGE80', '_LLCPWT', '_RACE', '_STATE']
2018: 32 columns → ['ADDEPEV', 'CHECKUP1', 'CNCRAGE', 'CNCRTYP', 'CSRVDOC1', 'CSRVPAIN', 'CSRVTRT', 'CVDCRHD4', 'CVDINFR4', 'CVDSTRK3', 'DIABETE', 'DRVISITS', 'EDUCA', 'EXERANY2', 'GENHLTH', 'HLTHPLN', 'INCOME', 'IYEAR', 'MARITAL', 'MEDCOST_U', 'MENTHLTH', 'PERSDOC', 'PHYSHLTH', 'POORHLTH', 'SEX', 'SLEPTIM1', 'SMOKE100', 'YEAR', '_AGE80', '_LLCPWT', '_RACE', '_STATE']
2019: 30 columns → ['ADDEPEV', 'CHECKUP1', 'CNCRAGE', 'CNCRTYP', 'CSRVDOC1', 'CSRVPAIN', 'CSRVTRT', 'CVDCRHD4', 'CVDINFR4', 'CVDSTRK3', 'DIABETE', 'EDUCA', 'EXERANY2', 'GENHLTH', 'HLTHPLN', 'INCOME', 'IYEAR', 'MARITAL', 'MEDCOST_U', 'MENTHLTH', 'PERSDOC', 'PHYSHLTH', 'POORHLTH', 'SEX', 'SMOKE100', 'YEAR', '_AGE80', '_LLCPWT', '_RACE', '_STATE']
2020: 31 columns → ['ADDEPEV', 'CHECKUP1', 'CNCRAGE', 'CNCRTYP', 'CSRVDOC1', 'CSRVPAIN', 'CSRVTRT', 'CVDCRHD4', 'CVDINFR4', 'CVDSTRK3', 'DIABETE', 'EDUCA', 'EXERANY2', 'GENHLTH', 'HLTHPLN', 'INCOME', 'IYEAR', 'MARITAL', 'MEDCOST_U', 'MENTHLTH', 'PERSDOC', 'PHYSHLTH', 'POORHLTH', 'SEX', 'SLEPTIM1', 'SMOKE100', 'YEAR', '_AGE80', '_LLCPWT', '_RACE', '_STATE']
2021: 30 columns → ['ADDEPEV', 'CHECKUP1', 'CNCRAGE', 'CNCRTYP', 'CSRVDOC1', 'CSRVPAIN', 'CSRVTRT', 'CVDCRHD4', 'CVDINFR4', 'CVDSTRK3', 'DIABETE', 'EDUCA', 'EXERANY2', 'GENHLTH', 'HLTHPLN', 'INCOME', 'IYEAR', 'MARITAL', 'MEDCOST_U', 'MENTHLTH', 'PERSDOC', 'PHYSHLTH', 'POORHLTH', 'SEX', 'SMOKE100', 'YEAR', '_AGE80', '_LLCPWT', '_RACE', '_STATE']
2022: 31 columns → ['ADDEPEV', 'CHECKUP1', 'CNCRAGE', 'CNCRTYP', 'CSRVDOC1', 'CSRVPAIN', 'CSRVTRT', 'CVDCRHD4', 'CVDINFR4', 'CVDSTRK3', 'DIABETE', 'EDUCA', 'EXERANY2', 'GENHLTH', 'HLTHPLN', 'INCOME', 'IYEAR', 'MARITAL', 'MEDCOST_U', 'MENTHLTH', 'PERSDOC', 'PHYSHLTH', 'POORHLTH', 'SEX', 'SLEPTIM1', 'SMOKE100', 'YEAR', '_AGE80', '_LLCPWT', '_RACE', '_STATE']
2023: 30 columns → ['ADDEPEV', 'CHECKUP1', 'CNCRAGE', 'CNCRTYP', 'CSRVDOC1', 'CSRVPAIN', 'CSRVTRT', 'CVDCRHD4', 'CVDINFR4', 'CVDSTRK3', 'DIABETE', 'EDUCA', 'EXERANY2', 'GENHLTH', 'HLTHPLN', 'INCOME', 'IYEAR', 'MARITAL', 'MEDCOST_U', 'MENTHLTH', 'PERSDOC', 'PHYSHLTH', 'POORHLTH', 'SEX', 'SMOKE100', 'YEAR', '_AGE80', '_LLCPWT', '_RACE', '_STATE']
2024: 30 columns → ['ADDEPEV', 'CHECKUP1', 'CNCRAGE', 'CNCRTYP', 'CSRVDOC1', 'CSRVPAIN', 'CSRVTRT', 'CVDCRHD4', 'CVDINFR4', 'CVDSTRK3', 'DIABETE', 'EDUCA', 'EXERANY2', 'GENHLTH', 'HLTHPLN', 'INCOME', 'IYEAR', 'MARITAL', 'MEDCOST_U', 'MENTHLTH', 'PERSDOC', 'PHYSHLTH', 'POORHLTH', 'SEX', 'SMOKE100', 'YEAR', '_AGE80', '_LLCPWT', '_RACE', '_STATE']

In [34]:
# Find the union of all columns
all_cols = set()
for df in all_years:
    all_cols.update(df.columns.tolist())

# Check which columns are missing per year
for df in all_years:
    year = int(df['YEAR'].iloc[0])
    missing = all_cols - set(df.columns.tolist())
    if missing:
        print(f"{year}: Missing → {sorted(missing)}")
    else:
        print(f"{year}: ✅ Complete")

2014: ✅ Complete
2016: ✅ Complete
2017: ✅ Complete
2018: ✅ Complete
2019: Missing → ['DRVISITS', 'SLEPTIM1']
2020: Missing → ['DRVISITS']
2021: Missing → ['DRVISITS', 'SLEPTIM1']
2022: Missing → ['DRVISITS']
2023: Missing → ['DRVISITS', 'SLEPTIM1']
2024: Missing → ['DRVISITS', 'SLEPTIM1']

In [10]:
# Step 1: Ensure all DataFrames have the exact same columns and order before concatenation
for i, df in enumerate(all_years):
    # Add any missing columns from selected_columns as pd.NA (or NaN)
    for col in selected_columns:
        if col not in df.columns:
            df[col] = pd.NA
    
    # Reorder columns to match selected_columns exactly, plus the 'YEAR' column at the end
    all_years[i] = df[selected_columns + ['YEAR']]

# Step 2: Visual check — Verify that every single DataFrame now has identical columns
print("=== Visual Check of Harmonized Columns per Year ===")
for df in all_years:
    year = int(df['YEAR'].iloc[0])
    print(f"{year}: {len(df.columns)} columns → Matches selected_columns? {list(df.columns[:-1]) == selected_columns}")

# Step 3: Concatenate all yearly datasets into one master dataset
df_combined = pd.concat(all_years, ignore_index=True)

# Step 4: Final verification outputs
print("\n=== Master Dataset Summary ===")
print(f"Master dataset successfully created!")
print(f"Total shape (Rows, Columns): {df_combined.shape}")
print(f"Unique years included: {sorted(df_combined['YEAR'].unique())}")

=== Visual Check of Harmonized Columns per Year ===
2014: 32 columns → Matches selected_columns? True
2016: 32 columns → Matches selected_columns? True
2017: 32 columns → Matches selected_columns? True
2018: 32 columns → Matches selected_columns? True
2019: 32 columns → Matches selected_columns? True
2020: 32 columns → Matches selected_columns? True
2021: 32 columns → Matches selected_columns? True
2022: 32 columns → Matches selected_columns? True
2023: 32 columns → Matches selected_columns? True
2024: 32 columns → Matches selected_columns? True

=== Master Dataset Summary ===
Master dataset successfully created!
Total shape (Rows, Columns): (117281, 32)
Unique years included: [np.int64(2014), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]

In [11]:
# Step 1: Check for duplicate rows in the combined master dataset
duplicates_count = df_combined.duplicated().sum()
print(f"Number of exact duplicate rows found: {duplicates_count}")

# If there are duplicates, drop them
if duplicates_count > 0:
    df_combined = df_combined.drop_duplicates().reset_index(drop=True)
    print(f"Duplicates removed. New shape: {df_combined.shape}")
else:
    print("No duplicate rows found. Dataset is clean.")

# Step 2: Check missing values per column to ensure structural missingness is as expected
print("\n=== Missing Values Summary (Top columns with missing data) ===")
missing_counts = df_combined.isnull().sum()
missing_pct = (missing_counts / len(df_combined)) * 100
missing_df = pd.DataFrame({'Missing Count': missing_counts, 'Missing Percentage (%)': missing_pct})
print(missing_df[missing_df['Missing Count'] > 0])

Number of exact duplicate rows found: 1
Duplicates removed. New shape: (117280, 32)

=== Missing Values Summary (Top columns with missing data) ===
          Missing Count  Missing Percentage (%)
PHYSHLTH              1                0.000853
POORHLTH          51531               43.938438
CNCRTYP             120                0.102319
CSRVTRT           36259               30.916610
CSRVDOC1          65669               55.993349
CSRVPAIN          41170               35.104025
INCOME               14                0.011937
_RACE                 6                0.005116
CVDINFR4              1                0.000853
SMOKE100             74                0.063097
EXERANY2              1                0.000853
SLEPTIM1          49745               42.415587
MARITAL               1                0.000853
DRVISITS         109841               93.657060

In [14]:
# 1. Visual inspection of the master dataset
print("=== Master Dataset Sample (First 5 rows) ===")
display(df_combined.head())

print("\n=== Master Dataset Tail (Last 5 rows) ===")
display(df_combined.tail())

# 2. Save to processed folder as CSV (robust & safe)
output_path = '../Data/data_processed/BRFSS_cancer_master_harmonized.csv'
df_combined.to_csv(output_path, index=False)

print(f"\nMaster harmonized dataset successfully saved to: {output_path}")

=== Master Dataset Sample (First 5 rows) ===

,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,CNCRAGE,CNCRTYP,CSRVTRT,CSRVDOC1,CSRVPAIN,_AGE80,...,SMOKE100,EXERANY2,SLEPTIM1,IYEAR,_STATE,MARITAL,CHECKUP1,DRVISITS,_LLCPWT,YEAR
0,1.0,15.0,88.0,15.0,45.0,22.0,2.0,2.0,2.0,61.0,...,2.0,1.0,8.0,b'2014',2.0,2.0,1.0,6.0,50.542747,2014
1,4.0,10.0,5.0,3.0,33.0,8.0,2.0,10.0,2.0,41.0,...,2.0,1.0,7.0,b'2014',2.0,1.0,2.0,12.0,290.360144,2014
2,3.0,7.0,88.0,88.0,57.0,1.0,2.0,7.0,1.0,59.0,...,1.0,1.0,3.0,b'2014',2.0,2.0,1.0,12.0,85.250540,2014
3,4.0,88.0,88.0,NaN,52.0,21.0,2.0,2.0,2.0,71.0,...,1.0,1.0,8.0,b'2014',2.0,2.0,1.0,3.0,156.116143,2014
4,2.0,3.0,88.0,88.0,47.0,2.0,2.0,2.0,2.0,80.0,...,2.0,1.0,9.0,b'2014',2.0,1.0,1.0,4.0,89.246612,2014

=== Master Dataset Tail (Last 5 rows) ===

,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,CNCRAGE,CNCRTYP,CSRVTRT,CSRVDOC1,CSRVPAIN,_AGE80,...,SMOKE100,EXERANY2,SLEPTIM1,IYEAR,_STATE,MARITAL,CHECKUP1,DRVISITS,_LLCPWT,YEAR
117275,2.0,88.0,5.0,3.0,37.0,77.0,2.0,3.0,NaN,48.0,...,1.0,1.0,<NA>,b'2024',78.0,1.0,1.0,<NA>,39.158119,2024
117276,4.0,25.0,30.0,3.0,33.0,16.0,2.0,5.0,NaN,37.0,...,1.0,1.0,<NA>,b'2024',78.0,4.0,4.0,<NA>,130.348392,2024
117277,3.0,4.0,88.0,88.0,48.0,5.0,1.0,NaN,NaN,55.0,...,2.0,1.0,<NA>,b'2024',78.0,5.0,1.0,<NA>,1.398864,2024
117278,3.0,88.0,88.0,NaN,49.0,6.0,2.0,5.0,NaN,51.0,...,2.0,1.0,<NA>,b'2024',78.0,5.0,1.0,<NA>,19.789338,2024
117279,3.0,88.0,88.0,NaN,43.0,22.0,2.0,5.0,NaN,57.0,...,1.0,1.0,<NA>,b'2024',78.0,1.0,2.0,<NA>,3.445776,2024

Master harmonized dataset successfully saved to: ../Data/data_processed/BRFSS_cancer_master_harmonized.csv